{"job_id": 249, "Status": "Error Traceback (most recent call last):\n  File \"/app/file_process/Resume_Scoring.py\", line 1421, in process_file\n    return resp, start_time, time.time()\n  File \"/app/file_process/Resume_Scoring.py\", line 1165, in main\n    df_Resume_scores = df_Resume_scores[\n  File \"/usr/local/lib/python3.8/site-packages/pandas/core/frame.py\", line 3811, in __getitem__\n    indexer = self.columns._get_indexer_strict(key, \"columns\")[1]\n  File \"/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py\", line 6108, in _get_indexer_strict\n    self._raise_if_missing(keyarr, indexer, axis_name)\n  File \"/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py\", line 6171, in _raise_if_missing\n    raise KeyError(f\"{not_found} not in index\")\nKeyError: \"['Current_Title', 'CurrentCompany'] not in index\"\n", "File": "", "Percent": 25, "Error_code": 1}