{"job_id": 304, "Status": "Error Traceback (most recent call last):\n  File \"/app/file_process/Resume_Scoring.py\", line 1473, in process_file\n    resp = main(org_file_list, job_folder, jd_input, experience, mandatory_skills, secondary_skills)\n  File \"/app/file_process/Resume_Scoring.py\", line 1160, in main\n    print(\"Length of columns to assign:\", len(exp_df[['Total_Exp_With_Years','Total_Gaps_With_Years']]))\n  File \"/usr/local/lib/python3.8/site-packages/pandas/core/frame.py\", line 3811, in __getitem__\n    indexer = self.columns._get_indexer_strict(key, \"columns\")[1]\n  File \"/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py\", line 6108, in _get_indexer_strict\n    self._raise_if_missing(keyarr, indexer, axis_name)\n  File \"/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py\", line 6168, in _raise_if_missing\n    raise KeyError(f\"None of [{key}] are in the [{axis_name}]\")\nKeyError: \"None of [Index(['Total_Exp_With_Years', 'Total_Gaps_With_Years'], dtype='object')] are in the [columns]\"\n", "File": "", "Percent": 25, "Error_code": 1}